export const LOGIN = 'LOGIN'
export const CREARUSUARIO = 'CREARUSUARIO'
export const RESERVARHOTEL = 'RESERVARHOTEL'
export const CERRARSESION = 'CERRARSESION'
export const ACTUALIZARUSUARIO = 'ACTUALIZARUSUARIO'




//!Reservas
export const LISTADERESERVAS = 'LISTADERESERVAS'
export const ITEMAPROBADO = 'ITEMAPROBADO'
export const ELIMINARRESERVA = 'ELIMINARRESERVA'
export const LISTADOPAQUETESALL = 'LISTADOPAQUETESALL'


//!Administrador 

export const ADMINCREARPAQUETE = 'ADMINCREARPAQUETE'
export const ADMINLISTAPAQUETES = 'ADMINLISTAPAQUETES'
export const ELIMINARPAQUETE = 'ELIMINARPAQUETE'
export const ADMINACTUALIZARPAQUETE = 'ADMINACTUALIZARPAQUETE'
export const LISTAUSUARIOSALL = 'LISTAUSUARIOSALL'
